import { Inter } from "next/font/google";
import "./globals.css";
// import Image from "next/image";
// import logo from "/public/logo.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="header">
          <p>
            <span>(주)</span> 도스이엔지
          </p>
          {/* <div className="logo">
            <Image src={logo} alt="" />
          </div> */}
        </div>
        {children}
      </body>
    </html>
  );
}
